### PR TITLE
fix: add an alias/name check during app create

### LINKED ISSUE #656: prevent link on same alias
Prevent users to link 2 applications with the same alias

this can cause exceptions on other commands

### PR DESCRIPTION
**Pull request by davlgd**
Fix #656

### CODE REVIEW

File: src/models/app_configuration.js [hunk 1]
```diff
@@ -63,7 +63,7 @@ async function removeLinkedApplication (alias) {
 };
 
 function findApp (config, alias) {
-
+
```
Comment (miton18) [inline src/models/app_configuration.js:66]: useless

File: src/models/app_configuration.js [hunk 2]
```diff
@@ -82,6 +82,20 @@ function findApp (config, alias) {
   return findDefaultApp(config);
 }
 
+function checkAlreadyLinked (apps, name, alias) {
+
+  const appAliasExists = apps.some(app => alias && app.alias === alias);
+  const appNameExists = apps.some(app => app.name === name);
```
Comment (miton18) [inline src/models/app_configuration.js:88]: can you group the expression with the condition ?

**Review by miton18 — CHANGES_REQUESTED** [review]

File: src/models/app_configuration.js (hunk 2 above)
Comment (hsablonniere) [inline src/models/app_configuration.js:88]: nitpick: we try to alway use parens on arrow functions, can you add them?

```js
  const appAliasExists = apps.some((app) => alias && app.alias === alias);
  const appNameExists = apps.some((app) => app.name === name);
```

File: src/models/app_configuration.js [hunk 3]
```diff
@@ -82,6 +82,20 @@ function findApp (config, alias) {
   return findDefaultApp(config);
 }
 
+function checkAlreadyLinked (apps, name, alias) {
+
+  const appAliasExists = apps.some(app => alias && app.alias === alias);
```
Comment (hsablonniere) [inline src/models/app_configuration.js:87]: nitpick: we try to avoid implicit null test and always use `!= null`. Can add it?

```
  const appAliasExists = apps.some((app) => alias != null && app.alias === alias);
```

**Review by hsablonniere — CHANGES_REQUESTED** [review]
Hey @davlgd, thank you for this. I added a few nitpicks but we tested the branch and it works great!

File: src/models/app_configuration.js [hunk 4]
```diff
@@ -82,6 +81,18 @@ function findApp (config, alias) {
   return findDefaultApp(config);
 }
 
+function checkAlreadyLinked (apps, name, alias) {
+  const appAliasExists = apps.some((app) => app.alias !=null &&  app.alias === alias);
```
Comment (miton18) [inline src/models/app_configuration.js:85]:
```suggestion
  const appAliasExists = apps.some((app) => app.alias != null && app.alias === alias);
```

**Review by miton18 — APPROVED** [review]
