### PR TITLE
Fix "clever restart" with short commit ids

### LINKED ISSUE #167: Restarting an application with a commit string shorter than expected tries to deploy commit #Infinity
```
clever restart --commit 94e54206
Restarting <Project> on commit #Infinity
```

Using the full commit ID works as intended. I don't know if we can get the full commit ID from the short commit ID but we don't want to try to deploy the `#Infinity` commit anyway :)

### PR DESCRIPTION
**Pull request by hsablonniere**
* Fix wrong coercion with some short commit ids (especially those looking like an exponential)
* Resolve full commit ids through local git repo

Fixes #167

### CODE REVIEW

**Comment by hsablonniere** [comment]
I'm not so sure about the unit test for `Git.resolveFullCommitId()` since it relies on an external test repo. WDTY?

**Comment by hsablonniere** [comment]
I also applied the boyscout mantra so I reworked the `restart` function a bit with some ES6!

File: src/commands/deploy.js [hunk 1]
```diff
@@ -55,26 +55,31 @@ deploy.deploy = function(api, params) {
...
-    Logger.println("Restarting " + app_data.name + suffix);
-    return Application.redeploy(api, app_data.app_id, app_data.org_id, commitId, withoutCache);
-  }).toProperty();
+  const { alias, quiet, commit, 'without-cache': withoutCache } = params.options
+
+  const s_fullCommitId = Git.resolveFullCommitId(commit)
+  s_fullCommitId.onError((e) => {
+      Logger.error(`Commit id ${commit} is ambiguous`)
+      process.exit(1);
+    })
```
Comment (divarvel) [inline src/commands/deploy.js]: I try to avoid early returns, would it be possible to return an error stream and let the error be managed only at the end?

File: src/commands/deploy.js [hunk 2]
```diff
@@ -55,26 +55,31 @@ deploy.deploy = function(api, params) {
...
-    var suffix = "";
-    if(commitId) suffix += " on commit #" + commitId;
-    if(withoutCache) suffix += " without using cache";
-
-    Logger.println("Restarting " + app_data.name + suffix);
-    return Application.redeploy(api, app_data.app_id, app_data.org_id, commitId, withoutCache);
-  }).toProperty();
+  const { alias, quiet, commit, 'without-cache': withoutCache } = params.options
+
+  const s_fullCommitId = Git.resolveFullCommitId(commit)
```
Comment (divarvel) [inline src/commands/deploy.js]: what happens if no commit is given?

Comment (hsablonniere) [reply src/commands/deploy.js]: It fails :scream: (fixing in progress...)

File: spec/git.spec.js [hunk 3]
```diff
@@ -97,6 +97,16 @@ describe("git", function() {
     });
   });
 
+  it("should be able lookup a full commit id", function(done) {
```
Comment (divarvel) [inline spec/git.spec.js]: "to lookup"

File: src/models/git.js [hunk 4]
```diff
@@ -184,6 +184,18 @@ module.exports = function(repositoryPath) {
     });
   };
 
+  Git.resolveFullCommitId = function(commitId) {
+    if (commitId == null) {
+      return Bacon.constant(null);
+    }
```
Comment (divarvel) [inline src/models/git.js]: I'd prefer to have the null checked outside of this function
