### PR TITLE
Limit the number of retries for when the WebSocket connexion fails

### LINKED ISSUE #294: `clever deploy` not exiting on deployment success
We are migrating our CI to `v1.1.1` and we observed that `clever deploy` did not exit upon deployment success.

Looking at the code in the stream command handler, I see an explicit `process.exit` for errors, but not for the end of the stream. [0]

I've witnessed a few times with bacon that sometimes the process keeps running even though we've got to the end of a stream. I guess it's because there is still an active event listener registered somewhere.

In the case of `clever deploy` (or `clever restart`), i feel that an explicit exit at the end of the deployment would be safer_

[0]: https://github.com/CleverCloud/clever-tools/blob/master/src/command-stream-handler.js#L6

### PR DESCRIPTION
**Pull request by hsablonniere**
Fixes #294 & #296

### CODE REVIEW

File: src/models/ws-stream.js [hunk 1]
```diff
@@ -31,13 +34,13 @@ function openWebSocket (url, authorization) {
...
     ws.on('close', () => {
-      Logger.debug('Websocket closed.');
+      Logger.debug('WebSocket closed.');
       clearInterval(pingInterval);
       sink(new Bacon.End());
     });
 
     ws.on('error', () => {
-      Logger.debug('Websocket closed.');
+      Logger.debug('WebSocket closed.');
```
Comment (clementd-fretlink) [inline src/models/ws-stream.js]: Maybe log the error and put a different message to distinguish between normal closing and errors? Having the same messages made debugging more difficult

Comment (hsablonniere) [reply src/models/ws-stream.js]: Good catch.

**Comment by hsablonniere** [comment]
@clementd-fretlink I also returned a `Bacon.Error` in the sink.
